spring:
  jpa:
    hibernate:
      ddl-auto: validate  # Não altera estrutura
  datasource:
    url: jdbc:postgresql://localhost:5432/springlabDB

# Desativa o DataInitializer
data:
  initializer:
    enabled: false