# Nome da aplicação
spring.application.name=spring-lab

# Porta do servidor (padrão 8080)
server.port=8080

# Configurações de logging
logging.level.com.rojudo.spring_lab=DEBUG
logging.level.org.springframework.web=INFO

# Mostrar mais detalhes de erro
server.error.include-message=always
server.error.include-binding-errors=always

# Configuração para JSON (Jackson)
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output=true